apiVersion: v1
kind: Namespace
metadata:
  name: traefik-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: users-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: orders-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: products-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: notify-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: database-namespace
