apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: auth-api-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: auth-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-worker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: auth-worker-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: auth-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockpit-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: cockpit-api-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cockpit-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockpit-worker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: cockpit-worker-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cockpit-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: social-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: social-api-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: social-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: social-worker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: social-worker-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: social-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: task-api-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: task-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-worker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: task-worker-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: task-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: vault-api-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-worker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: vault-worker-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflow-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: workflow-api-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: workflow-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflow-worker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: workflow-worker-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: workflow-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messenger-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: messenger-api-helm
    targetRevision: 0.1.2
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: messenger-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---

