apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: auth-api-helm
    targetRevision: 0.1.0
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: auth-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-worker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry
    chart: auth-worker-helm
    targetRevision: 0.1.0
    helm:
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: auth-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
