apiVersion: v1
kind: Pod
metadata:
  name: get-messenger-socket
  namespace: auth-namespace
spec:
  containers:
  - name: app
    image: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/messenger-api:0.0.1
    command: ["cat", "/app/dist/socket.js"]
  imagePullSecrets:
  - name: ecr-registry-secret
  restartPolicy: Never
