chartTags:
  metallb: "1.0.0"
  postgres: "1.0.0"
  pgbouncer: "1.0.0"
  redis: "1.0.0"
  traefik: "1.0.0"
  opa-gatekeeper: "1.0.0"
  auth-api: "1.0.0"
  auth-worker: "1.0.0"
  cockpit-api: "1.0.0"
  cockpit-worker: "1.0.0"
  messenger-api: "1.0.0"
  social-api: "1.0.0"
  social-worker: "1.0.0"
  task-api: "1.0.0"
  task-worker: "1.0.0"
  vault-api: "1.0.0"
  vault-worker: "1.0.0"
  workflow-api: "1.0.0"
  workflow-worker: "1.0.0"
