global:
  argocdNamespace: argocd
  destinationServer: https://kubernetes.default.svc
  ecrRepoUrl: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry

chartTags:
  metallb: "1.0.0"
  postgres: "1.0.0"
  pgbouncer: "1.0.0"
  redis: "1.0.0"
  traefik: "1.0.0"
  opa-gatekeeper: "1.0.0"
  auth-api: "0.0.6"
  auth-worker: "0.0.6"
  cockpit-api: "0.0.2"
  cockpit-worker: "0.0.2"
  messenger-api: "0.0.1"
  social-api: "0.0.3"
  social-worker: "0.0.3"
  task-api: "0.0.3"
  task-worker: "0.0.3"
  vault-api: "0.0.3"
  vault-worker: "0.0.3"
  workflow-api: "0.0.3"
  workflow-worker: "0.0.3"

applications:
  metallb:
    chart: metallb-helm
    namespace: metallb-system
    syncWave: "1"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
  postgres:
    chart: postgres-helm
    namespace: database-namespace
    syncWave: "2"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  pgbouncer:
    chart: pgbouncer-helm
    namespace: database-namespace
    syncWave: "3"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  redis:
    chart: redis-helm
    namespace: database-namespace
    syncWave: "3"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  traefik:
    chart: traefik-helm
    namespace: traefik-ingress
    syncWave: "4"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
  opa-gatekeeper:
    chart: opa-gatekeeper-helm
    namespace: gatekeeper-system
    syncWave: "5"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
  auth-api:
    chart: auth-api-helm
    namespace: auth-namespace
    syncWave: "10"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
      probes:
        readiness:
          path: /api/health
        liveness:
          path: /api/health
  auth-worker:
    chart: auth-worker-helm
    namespace: auth-namespace
    syncWave: "20"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
  cockpit-api:
    chart: cockpit-api-helm
    namespace: cockpit-namespace
    syncWave: "12"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
      probes:
        readiness:
          path: /api/health
        liveness:
          path: /api/health
  cockpit-worker:
    chart: cockpit-worker-helm
    namespace: cockpit-namespace
    syncWave: "22"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
  messenger-api:
    chart: messenger-api-helm
    namespace: messenger-namespace
    syncWave: "10"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
      probes:
        liveness:
          path: /socket.io/socket.io.js
        readiness:
          path: /socket.io/socket.io.js
  social-api:
    chart: social-api-helm
    namespace: social-namespace
    syncWave: "13"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
      probes:
        readiness:
          path: /api/health
        liveness:
          path: /api/health
  social-worker:
    chart: social-worker-helm
    namespace: social-namespace
    syncWave: "23"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
  task-api:
    chart: task-api-helm
    namespace: task-namespace
    syncWave: "14"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
      probes:
        readiness:
          path: /api/health
        liveness:
          path: /api/health
  task-worker:
    chart: task-worker-helm
    namespace: task-namespace
    syncWave: "24"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
  vault-api:
    chart: vault-api-helm
    namespace: vault-namespace
    syncWave: "11"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
      probes:
        readiness:
          path: /api/health
        liveness:
          path: /api/health
  vault-worker:
    chart: vault-worker-helm
    namespace: vault-namespace
    syncWave: "21"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
  workflow-api:
    chart: workflow-api-helm
    namespace: workflow-namespace
    syncWave: "16"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
      probes:
        readiness:
          path: /api/health
        liveness:
          path: /api/health
  workflow-worker:
    chart: workflow-worker-helm
    namespace: workflow-namespace
    syncWave: "26"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    helmValues:
      replicaCount: 1
      hpa:
        enabled: false
        minReplicas: 1
      affinity:
        podAntiAffinity:
          enabled: false
      topologySpreadConstraints:
        enabled: false
