global:
  argocdNamespace: argocd
  destinationServer: https://kubernetes.default.svc
  ecrRepoUrl: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry

chartTags:
  metallb: "1.0.0"
  postgres: "1.0.0"
  pgbouncer: "1.0.0"
  redis: "1.0.0"
  traefik: "1.0.0"
  opa-gatekeeper: "1.0.0"

applications:
  metallb:
    chart: metallb-helm
    namespace: metallb-system
    syncWave: "1"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
  postgres:
    chart: postgres-helm
    namespace: database-namespace
    syncWave: "2"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  pgbouncer:
    chart: pgbouncer-helm
    namespace: database-namespace
    syncWave: "3"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  redis:
    chart: redis-helm
    namespace: database-namespace
    syncWave: "3"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  traefik:
    chart: traefik-helm
    namespace: traefik-ingress
    syncWave: "4"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
  opa-gatekeeper:
    chart: opa-gatekeeper-helm
    namespace: gatekeeper-system
    syncWave: "5"
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
