imagePullSecrets:
  - name: ecr-registry-secret

services:
  auth:
    replicas: 2
    hpa:
      minReplicas: 2
      maxReplicas: 10
    api:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/auth-api
      tag: 0.0.0.27
    worker:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/auth-worker
      tag: 0.0.0.20
  cockpit:
    replicas: 2
    hpa:
      minReplicas: 2
      maxReplicas: 10
    api:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/cockpit-api
      tag: local-test-1
    worker:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/cockpit-worker
      tag: local-test-1
  messenger:
    replicas: 2
    hpa:
      minReplicas: 2
      maxReplicas: 10
    api:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/messenger-api
      tag: local-test-1
  social:
    replicas: 2
    hpa:
      minReplicas: 2
      maxReplicas: 10
    api:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/social-api
      tag: local-test-1
    worker:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/social-worker
      tag: 0.0.0.15
  task:
    replicas: 2
    hpa:
      minReplicas: 2
      maxReplicas: 10
    api:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/task-api
      tag: 0.0.0.16
    worker:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/task-worker
      tag: 0.0.0.16
  vault:
    replicas: 2
    hpa:
      minReplicas: 2
      maxReplicas: 10
    api:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/vault-api
      tag: local-test-1
    worker:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/vault-worker
      tag: 0.0.0.13
  workflow:
    replicas: 2
    hpa:
      minReplicas: 2
      maxReplicas: 10
    api:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/workflow-api
      tag: local-test-1
    worker:
      repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/workflow-worker
      tag: local-test-1
