apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "vault-api.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  DB_SCHEMA: {{ .Values.config.dbSchema | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  DB_SSL: {{ .Values.config.dbSsl | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  REDIS_PASSWORD: {{ .Values.config.redisPassword | quote }}
  JWT_ALGORITHM: {{ .Values.config.jwtAlgorithm | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  ENV: {{ .Values.config.env | quote }}
  WORKER_ENABLED: {{ .Values.config.workerEnabled | quote }}
