apiVersion: v1
kind: Namespace
metadata:
  name: traefik-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: cockpit-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: messenger-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: social-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: task-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: workflow-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: database-namespace