apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: traefik-ingress
spec:
  rateLimit:
    average: {{ .Values.rateLimit.average }}
    burst: {{ .Values.rateLimit.burst }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: traefik-ingress
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsPreload: true
    stsSeconds: 31536000
    customFrameOptionsValue: SAMEORIGIN
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jwt-auth
  namespace: traefik-ingress
spec:
  plugin:
    jwt-verification:
      secret: {{ .Values.jwt.secret | quote }}
      algorithms:
        - HS256
      headerName: Authorization
      headerValuePrefix: Bearer
