apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.azureKeyVault.storeName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: {{ .Values.azureKeyVault.vaultUrl | quote }}
      tenantId: {{ .Values.azureKeyVault.tenantId | quote }}
      authSecretRef:
        clientId:
          name: {{ .Values.azureKeyVault.authSecret.name | quote }}
          key: {{ .Values.azureKeyVault.authSecret.clientIdKey | quote }}
          namespace: {{ .Values.azureKeyVault.authSecret.namespace | quote }}
        clientSecret:
          name: {{ .Values.azureKeyVault.authSecret.name | quote }}
          key: {{ .Values.azureKeyVault.authSecret.clientSecretKey | quote }}
          namespace: {{ .Values.azureKeyVault.authSecret.namespace | quote }}
