namespace:
  name: social-namespace
  create: false

nameOverride: ""
fullnameOverride: social-worker

labels:
  managedBy: nitroberry

imagePullSecrets:
  - name: ecr-registry-secret

image:
  repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/social-worker
  tag: "0.0.0.20"
  pullPolicy: IfNotPresent

replicaCount: 2
strategyType: RollingUpdate

config:
  name: social-worker-config
  dbSchema: social
  dbHost: pgbouncer-service.database-namespace.svc.cluster.local
  dbPort: "6432"
  dbName: postgres
  dbUser: postgres
  dbSsl: disable
  redisHost: redis-service.database-namespace.svc.cluster.local
  redisPort: "6379"
  redisPassword: ""
  jwtAlgorithm: HS256
  logLevel: info
  env: production
  workerEnabled: "true"

secret:
  name: social-worker-secrets
  dbPassword: REPLACE_WITH_STRONG_PASSWORD
  jwtSecret: REPLACE_WITH_RANDOM_256BIT_SECRET

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

volumes:
  pm2Runtime:
    enabled: true
    mountPath: /home/node/.pm2
  appLogs:
    enabled: true
    mountPath: /app/logs

affinity:
  podAntiAffinity:
    enabled: true
    required: true
    topologyKey: kubernetes.io/hostname

topologySpreadConstraints:
  enabled: true
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule

networkPolicy:
  enabled: true
  name: social-worker-policy
  egress:
    databaseNamespace: database-namespace
    pgbouncerApp: pgbouncer
    pgbouncerPort: 6432
    redisApp: redis
    redisPort: 6379
