traefik:
  namespace: traefik-ingress
  replicas: 1
  image: traefik:v3.0
  serviceType: LoadBalancer
  acmeEmail: admin@nitroberry.com
  storage: 128Mi
rateLimit:
  average: 100
  burst: 50
jwt:
  secret: REPLACE_WITH_JWT_SECRET
