namespace:
  name: task-namespace
  create: true

nameOverride: ""
fullnameOverride: task-api

labels:
  managedBy: nitroberry

imagePullSecrets:
  - name: ecr-registry-secret

image:
  repository: 798701233691.dkr.ecr.ap-south-1.amazonaws.com/nitroberry/task-api
  tag: "0.0.0.27"
  pullPolicy: IfNotPresent

replicaCount: 2
strategyType: RollingUpdate

service:
  name: task-api-service
  port: 8080
  targetPort: 8080

config:
  name: task-api-config
  port: "8080"
  dbSchema: task
  dbHost: pgbouncer-service.database-namespace.svc.cluster.local
  dbPort: "6432"
  dbName: postgres
  dbUser: postgres
  dbSsl: disable
  redisHost: redis-service.database-namespace.svc.cluster.local
  redisPort: "6379"
  redisPassword: ""
  jwtAlgorithm: HS256
  logLevel: info
  env: production
  workerEnabled: "false"

secret:
  name: task-api-secrets
  dbPassword: REPLACE_WITH_STRONG_PASSWORD
  jwtSecret: REPLACE_WITH_RANDOM_256BIT_SECRET

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

probes:
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 20
    failureThreshold: 3

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

volumes:
  pm2Runtime:
    enabled: true
    mountPath: /home/node/.pm2
  appLogs:
    enabled: true
    mountPath: /app/logs

affinity:
  podAntiAffinity:
    enabled: true
    required: true
    topologyKey: kubernetes.io/hostname

topologySpreadConstraints:
  enabled: true
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuAverageUtilization: 70

ingressRoute:
  enabled: true
  name: task-api-websecure
  host: task.nitroberry.com
  entryPoints:
    - websecure
  tls:
    certResolver: myresolver
  middlewares:
    - name: rate-limit
      namespace: traefik-ingress
    - name: security-headers
      namespace: traefik-ingress

networkPolicy:
  enabled: true
  name: task-api-policy
  ingress:
    traefikNamespace: traefik-ingress
  egress:
    databaseNamespace: database-namespace
    pgbouncerApp: pgbouncer
    pgbouncerPort: 6432
    redisApp: redis
    redisPort: 6379
