chartTags:
  metallb: "1.0.0"
  postgres: "1.0.0"
  pgbouncer: "1.0.0"
  redis: "1.0.0"
  traefik: "1.0.0"
  opa-gatekeeper: "1.0.0"
  external-secrets: "1.0.0"
  external-secrets-config: "1.0.0"
  reloader: "1.0.0"
  auth-api: "0.0.45"
  auth-worker: "0.0.45"
  cockpit-api: "0.0.149"
  cockpit-worker: "0.0.149"
  messenger-api: "0.0.8"
  social-api: "0.0.40"
  social-worker: "0.0.40"
  task-api: "0.0.35"
  task-worker: "0.0.35"
  vault-api: "0.0.39"
  vault-worker: "0.0.39"
  workflow-api: "0.0.85"
  workflow-worker: "0.0.85"
