chartTags:
  metallb: "1.0.0"
  postgres: "1.0.0"
  pgbouncer: "1.0.0"
  redis: "1.0.0"
  traefik: "1.0.0"
  opa-gatekeeper: "1.0.0"
  external-secrets: "1.0.0"
  external-secrets-config: "1.0.0"
  reloader: "1.0.0"
  auth-api: "0.0.6"
  auth-worker: "0.0.6"
  cockpit-api: "0.0.2"
  cockpit-worker: "0.0.2"
  messenger-api: "0.0.1"
  social-api: "0.0.3"
  social-worker: "0.0.3"
  task-api: "0.0.3"
  task-worker: "0.0.3"
  vault-api: "0.0.3"
  vault-worker: "0.0.3"
  workflow-api: "0.0.3"
  workflow-worker: "0.0.3"
