{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressRoute.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "task-api.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingressRoute.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.ingressRoute.host }}`)
      kind: Rule
      services:
        - name: {{ .Values.service.name }}
          port: {{ .Values.service.port }}
      {{- with .Values.ingressRoute.middlewares }}
      middlewares:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  tls:
    certResolver: {{ .Values.ingressRoute.tls.certResolver }}
{{- end }}
