apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "workflow-api.labels" . | nindent 4 }}
    secret-type: app
type: Opaque
stringData:
  db-password: {{ .Values.secret.dbPassword | quote }}
  jwt-secret: {{ .Values.secret.jwtSecret | quote }}
  database-url: {{ include "workflow-api.databaseUrl" . | quote }}
